package MainApp;

public enum Error_Type {
    TAG_MISMATCH,
    FUNCTION_DUPLICATION,
    UNDECLARED_PROPERTY,
    VAR_NOT_EXIST,
    SINGLE_VALUED_VARIABLE,
    EVENT_NOT_EXIST,
    FUNCTION_ERROR_PARAMETER,
}
